#!/usr/bin/env python
# coding: utf-8

# In[1]:


# import libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


# In[2]:


# import dataset 
dataset=pd.read_csv("D:\LR dataset.csv")
dataset.head()


# In[5]:


x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,1].values


# In[7]:


# splitting the data set into train and test data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=0)


# In[8]:


X_train,X_test,y_train,y_test


# In[9]:


# importing Library For regression
from sklearn.linear_model import LinearRegression

reg= LinearRegression()

reg.fit(X_train,y_train)


# In[10]:


# Predicting the values
y_predict=reg.predict(X_test)
y_predict


# In[11]:


y_test


# In[12]:


# prediction training
plt.scatter(X_train, y_train, color='red', )
plt.plot(X_train,reg.predict(X_train), color='blue')
plt.title("Linear Regression salary vs experinces", size=18)
plt.xlabel("Year of Employee",size=15)
plt.ylabel("Saleries of Employee", size=15)
plt.show()


# In[13]:


# predicting for test values
plt.scatter(X_test, y_test, color='red')
plt.plot(X_test,reg.predict(X_test),color='Blue')
plt.title("linear regression salary vs experince", size=16)
plt.xlabel("Year of Employee", size=12)
plt.ylabel("Saleries of Employee", size=12)
plt.show()


# In[ ]:




